### ISSUE TITLE
Saving game is not proceeding

### ISSUE THREAD

**Issue by LecrisUT** [SamboyCoding/RimworldBetterLoading#6]
Under certain conditions, this mod breaks the game saving. Using only **BetterLoading**, **Harmony** and **HugsLib**, all the most recent versions.

Steps to reproduce: QuickStart a colony, Save a game
Symptoms:
- No saving game dialog pops up
- White text in top left saying Saved Game
- Save game is not displayed in load game
- You cannot even exit to main menu

I hope @UnlimitedHugs can pitch in as well.

**Comment by SamboyCoding** [comment]
Narrowed down to HugsLib not calling all the mod finalising methods when it has quickstart enabled, so betterloading doesn't think it's finished.

Fix implemented and tested working in https://github.com/SamboyCoding/RimworldBetterLoading/commit/26d689822157405881daa0b2725f1eb57f0723ac, will be released soon. Leaving open so I remember.

**Comment by UnlimitedHugs** [comment]
@SamboyCoding Which missing method call are you referring to?

**Comment by SamboyCoding** [comment]
@UnlimitedHugs Damn, I missed this, but it seems like one or more of HugsLibController#EnumerateChildMods, UpdateFeatureManager#InspectActiveMod, or one of the child mods' Initialize or DefsLoaded methods isn't being called when quickstarting, because the number it expects to be called is not equal to the number actually being called (which causes BL to get stuck without the HugsLib stage ever finishing).

As you can see in the workaround, I now just forcibly finish the stage once HugsLibController#LoadReloadInitialize finishes - which works fine.

**Comment by UnlimitedHugs** [comment]
@SamboyCoding All right, thanks for the info. I might need to investigate that on my end.
